spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            redirect-uri: ${server.url.back}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email, profile
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          kakao:
            client-id: 
            redirect-uri: ${server.url.back}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email, name

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
